List<Map<String, dynamic>> allfruits = [
  {
    'id': '1',
    'name': 'Banana',
    'image': 'assets/banana.png',
    'rating': '⭐ 4.8 (287)',
    'price': 'Rs.58',
    'description': 'Rich in flavor and nutrients...',
    'nutrition': {
      'Calories': '89 kcal',
      'Carbs': '23g',
      'Protein': '1.1g',
      'Fat': '0.3g',
    },
  },
  {
    'id': '2',
    'name': 'Apples',
    'image': 'assets/apple.png',
    'rating': '⭐ 4.8 (287)',
    'price': 'Rs.100',
    'description': 'Fresh from sustainable orchards...',
    'nutrition': {
      'Calories': '52 kcal',
      'Carbs': '14g',
      'Protein': '0.3g',
      'Fat': '0.2g',
    },
  },
  {
    'id': '3',
    'name': 'Oranges',
    'image': 'assets/orange.png',
    'rating': '⭐ 4.8 (287)',
    'price': 'Rs.110',
    'description': 'Sweet, tangy, and 100% organic...',
    'nutrition': {
      'Calories': '47 kcal',
      'Carbs': '12g',
      'Protein': '0.9g',
      'Fat': '0.1g',
    },
  },
  {
    'id': '4',
    'name': 'Mango',
    'image': 'assets/mango.png',
    'rating': '⭐ 4.9 (520)',
    'price': 'Rs.150',
    'description': 'Juicy, sweet, and irresistibly delicious...',
    'nutrition': {
      'Calories': '60 kcal',
      'Carbs': '15g',
      'Protein': '0.8g',
      'Fat': '0.4g',
    },
  },
  {
    'id': '5',
    'name': 'Strawberries',
    'image': 'assets/strawberry.png',
    'rating': '⭐ 4.8 (410)',
    'price': 'Rs.200',
    'description': 'Bright, sweet, and bursting with flavor...',
    'nutrition': {
      'Calories': '32 kcal',
      'Carbs': '8g',
      'Protein': '0.7g',
      'Fat': '0.3g',
    },
  },
  {
    'id': '6',
    'name': 'Watermelon',
    'image': 'assets/watermelon.png',
    'rating': '⭐ 4.7 (350)',
    'price': 'Rs.40/kg',
    'description': 'Refreshing and hydrating...',
    'nutrition': {
      'Calories': '30 kcal',
      'Carbs': '8g',
      'Protein': '0.6g',
      'Fat': '0.2g',
    },
  },
  {
    'id': '7',
    'name': 'Pineapple',
    'image': 'assets/pineapple.png',
    'rating': '⭐ 4.6 (295)',
    'price': 'Rs.90',
    'description': 'Tropical, tangy, and full of flavor...',
    'nutrition': {
      'Calories': '50 kcal',
      'Carbs': '13g',
      'Protein': '0.5g',
      'Fat': '0.1g',
    },
  },
  {
    'id': '8',
    'name': 'Blueberries',
    'image': 'assets/blueberries.png',
    'rating': '⭐ 4.9 (180)',
    'price': 'Rs.250',
    'description': 'Small but mighty, packed with antioxidants...',
    'nutrition': {
      'Calories': '57 kcal',
      'Carbs': '14g',
      'Protein': '0.7g',
      'Fat': '0.3g',
    },
  },
  {
    'id': '9',
    'name': 'Papaya',
    'image': 'assets/papaya.png',
    'rating': '⭐ 4.7 (320)',
    'price': 'Rs.80',
    'description': 'Naturally sweet and rich in vitamins...',
    'nutrition': {
      'Calories': '43 kcal',
      'Carbs': '11g',
      'Protein': '0.5g',
      'Fat': '0.2g',
    },
  },
  {
    'id': '10',
    'name': 'Grapes',
    'image': 'assets/grapes.png',
    'rating': '⭐ 4.8 (400)',
    'price': 'Rs.120',
    'description': 'Juicy and full of flavor...',
    'nutrition': {
      'Calories': '69 kcal',
      'Carbs': '18g',
      'Protein': '0.7g',
      'Fat': '0.2g',
    },
  },
  {
    'id': '11',
    'name': 'Kiwi',
    'image': 'assets/kiwi.png',
    'rating': '⭐ 4.7 (230)',
    'price': 'Rs.150',
    'description': 'Tangy, sweet, and rich in nutrients...',
    'nutrition': {
      'Calories': '61 kcal',
      'Carbs': '15g',
      'Protein': '1.1g',
      'Fat': '0.5g',
    },
  },
  {
    'id': '12',
    'name': 'Pomegranate',
    'image': 'assets/pomegranate.png',
    'rating': '⭐ 4.8 (310)',
    'price': 'Rs.180',
    'description': 'Rich in antioxidants...',
    'nutrition': {
      'Calories': '83 kcal',
      'Carbs': '19g',
      'Protein': '1.7g',
      'Fat': '1.2g',
    },
  },
  {
    'id': '13',
    'name': 'Avocado',
    'image': 'assets/avocado.png',
    'rating': '⭐ 4.9 (190)',
    'price': 'Rs.300',
    'description': 'Creamy, nutritious, and versatile...',
    'nutrition': {
      'Calories': '160 kcal',
      'Carbs': '9g',
      'Protein': '2g',
      'Fat': '15g',
    },
  },
];
