List<Map<String, dynamic>> pulses = [
  {
    'id': 'pulse_1',
    'name': 'Toor Dal',
    'image': 'assets/toor_dal.png',
    'price': 'Rs.140/kg',
    'rating': '⭐ 4.6 (500)',
    'description': 'Rich and nutritious toor dal, perfect for Indian curries.',
    'nutrition': {
      'Calories': '343 kcal',
      'Carbs': '58g',
      'Protein': '22g',
      'Fat': '1.5g',
    },
  },
  {
    'id': 'pulse_2',
    'name': 'Moong Dal',
    'image': 'assets/moong_dal.png',
    'price': 'Rs.120/kg',
    'rating': '⭐ 4.7 (450)',
    'description': 'Light and easy-to-digest moong dal for a healthy diet.',
    'nutrition': {
      'Calories': '347 kcal',
      'Carbs': '58g',
      'Protein': '24g',
      'Fat': '1.2g',
    },
  },
  {
    'id': 'pulse_3',
    'name': 'Chana Dal',
    'image': 'assets/chana_dal.png',
    'price': 'Rs.110/kg',
    'rating': '⭐ 4.8 (400)',
    'description': 'A protein-rich pulse that’s a staple in Indian cuisine.',
    'nutrition': {
      'Calories': '364 kcal',
      'Carbs': '61g',
      'Protein': '19g',
      'Fat': '6g',
    },
  },
  {
    'id': 'pulse_4',
    'name': 'Urad Dal',
    'image': 'assets/urad_dal.png',
    'price': 'Rs.150/kg',
    'rating': '⭐ 4.6 (350)',
    'description': 'Whole urad dal, ideal for dal makhani and idli batter.',
    'nutrition': {
      'Calories': '341 kcal',
      'Carbs': '57g',
      'Protein': '25g',
      'Fat': '1.4g',
    },
  },
  {
    'id': 'pulse_5',
    'name': 'Masoor Dal',
    'image': 'assets/lentils.png',
    'price': 'Rs.130/kg',
    'rating': '⭐ 4.7 (400)',
    'description': 'Iron-rich masoor dal, great for healthy soups and curries.',
    'nutrition': {
      'Calories': '352 kcal',
      'Carbs': '60g',
      'Protein': '24g',
      'Fat': '1.5g',
    },
  },
  {
    'id': 'pulse_6',
    'name': 'Kabuli Chana',
    'image': 'assets/kabuli_chana.png',
    'price': 'Rs.90/kg',
    'rating': '⭐ 4.8 (600)',
    'description': 'Versatile chickpeas, perfect for hummus or chole curry.',
    'nutrition': {
      'Calories': '364 kcal',
      'Carbs': '61g',
      'Protein': '19g',
      'Fat': '6g',
    },
  },
  {
    'id': 'pulse_7',
    'name': 'Rajma',
    'image': 'assets/rajma.png',
    'price': 'Rs.160/kg',
    'rating': '⭐ 4.9 (500)',
    'description': 'High-protein kidney beans, great for rajma chawal.',
    'nutrition': {
      'Calories': '333 kcal',
      'Carbs': '60g',
      'Protein': '24g',
      'Fat': '0.8g',
    },
  },
  {
    'id': 'pulse_8',
    'name': 'Green Peas',
    'image': 'assets/green_peas.png',
    'price': 'Rs.130/kg',
    'rating': '⭐ 4.7 (350)',
    'description': 'Dried green peas for hearty soups and curries.',
    'nutrition': {
      'Calories': '81 kcal',
      'Carbs': '14g',
      'Protein': '5g',
      'Fat': '0.4g',
    },
  },
  {
    'id': 'pulse_9',
    'name': 'Black Chana',
    'image': 'assets/black_chana.png',
    'price': 'Rs.90/kg',
    'rating': '⭐ 4.6 (400)',
    'description':
        'Nutritious black chickpeas, perfect for curries and snacks.',
    'nutrition': {
      'Calories': '360 kcal',
      'Carbs': '60g',
      'Protein': '19g',
      'Fat': '5.5g',
    },
  },
  {
    'id': 'pulse_10',
    'name': 'Horse Gram',
    'image': 'assets/horse_gram.png',
    'price': 'Rs.100/kg',
    'rating': '⭐ 4.5 (250)',
    'description':
        'High-fiber and protein-packed horse gram for traditional dishes.',
    'nutrition': {
      'Calories': '321 kcal',
      'Carbs': '57g',
      'Protein': '22g',
      'Fat': '0.6g',
    },
  },
];
