List<Map<String, dynamic>> snacks = [
  {
    'name': 'Nachos',
    'image': 'assets/nachos.png',
    'price': 'Rs.150',
    'rating': '⭐ 4.8 (600)',
    'description': 'Crispy nachos served with tangy tomato salsa.',
    'nutrition': {
      'Calories': '250 kcal',
      'Carbs': '30g',
      'Protein': '5g',
      'Fat': '10g',
    },
  },
  {
    'name': 'Rolls',
    'image': 'assets/spring_rolls.png',
    'price': 'Rs.120',
    'rating': '⭐ 4.7 (350)',
    'description':
        'Crispy fried rolls stuffed with fresh vegetables and spices.',
    'nutrition': {
      'Calories': '200 kcal',
      'Carbs': '22g',
      'Protein': '3g',
      'Fat': '9g',
    },
  },
  {
    'name': 'Fries',
    'image': 'assets/french_fries.png',
    'price': 'Rs.100',
    'rating': '⭐ 4.9 (700)',
    'description':
        'Golden and crispy French fries, perfect as a snack or side dish.',
    'nutrition': {
      'Calories': '312 kcal',
      'Carbs': '41g',
      'Protein': '3.4g',
      'Fat': '15g',
    },
  },
  {
    'name': 'Sandwich',
    'image': 'assets/sandwich.png',
    'price': 'Rs.140',
    'rating': '⭐ 4.8 (500)',
    'description': 'Grilled cheese sandwich with gooey, melted cheese inside.',
    'nutrition': {
      'Calories': '270 kcal',
      'Carbs': '30g',
      'Protein': '9g',
      'Fat': '12g',
    },
  },
  {
    'name': 'Burger',
    'image': 'assets/burger.png',
    'price': 'Rs.180',
    'rating': '⭐ 4.6 (450)',
    'description': 'Juicy veggie burger with fresh lettuce and tomato.',
    'nutrition': {
      'Calories': '350 kcal',
      'Carbs': '40g',
      'Protein': '12g',
      'Fat': '15g',
    },
  },
  {
    'name': 'Tacos',
    'image': 'assets/tacos.png',
    'price': 'Rs.160',
    'rating': '⭐ 4.9 (300)',
    'description': 'Soft tacos filled with fresh veggies and beans.',
    'nutrition': {
      'Calories': '200 kcal',
      'Carbs': '25g',
      'Protein': '6g',
      'Fat': '5g',
    },
  },
  {
    'name': 'Pasta',
    'image': 'assets/pasta.png',
    'price': 'Rs.200',
    'rating': '⭐ 4.8 (400)',
    'description': 'Creamy and delicious veggie pasta with fresh herbs.',
    'nutrition': {
      'Calories': '310 kcal',
      'Carbs': '40g',
      'Protein': '8g',
      'Fat': '10g',
    },
  },
  {
    'name': 'Popcorn',
    'image': 'assets/popcorn.png',
    'price': 'Rs.80',
    'rating': '⭐ 4.5 (700)',
    'description': 'Light and crunchy popcorn, perfect for snacking.',
    'nutrition': {
      'Calories': '100 kcal',
      'Carbs': '18g',
      'Protein': '3g',
      'Fat': '1g',
    },
  },
  {
    'name': 'Chips',
    'image': 'assets/chips.png',
    'price': 'Rs.50',
    'rating': '⭐ 4.6 (800)',
    'description': 'Crispy potato chips, a classic and tasty snack.',
    'nutrition': {
      'Calories': '150 kcal',
      'Carbs': '15g',
      'Protein': '2g',
      'Fat': '10g',
    },
  },
];
