List<Map<String, dynamic>> Spices = [
  {
    'id': 'spice_1',
    'name': 'Turmeric',
    'image': 'assets/turmeric.png',
    'rating': '⭐ 4.9 (500)',
    'price': 'Rs.120',
    'description':
        'Pure organic turmeric powder, known for its rich color and health benefits.',
    'nutrition': {
      'Calories': '312 kcal',
      'Carbs': '65g',
      'Protein': '9g',
      'Fat': '3g',
    },
  },
  {
    'id': 'spice_2',
    'name': 'Cumin Seeds',
    'image': 'assets/cumin.png',
    'rating': '⭐ 4.8 (450)',
    'price': 'Rs.150',
    'description':
        'Aromatic organic cumin seeds, perfect for adding earthy flavors.',
    'nutrition': {
      'Calories': '375 kcal',
      'Carbs': '44g',
      'Protein': '18g',
      'Fat': '22g',
    },
  },
  {
    'id': 'spice_3',
    'name': 'Coriander Powder',
    'image': 'assets/coriander.png',
    'rating': '⭐ 4.7 (400)',
    'price': 'Rs.140',
    'description': 'Fresh organic coriander powder with a citrusy aroma.',
    'nutrition': {
      'Calories': '298 kcal',
      'Carbs': '55g',
      'Protein': '12g',
      'Fat': '18g',
    },
  },
  {
    'id': 'spice_4',
    'name': 'Red Chilli Powder',
    'image': 'assets/redchilli.png',
    'rating': '⭐ 4.8 (480)',
    'price': 'Rs.130',
    'description':
        'Spicy and vibrant organic red chilli powder for fiery flavors.',
    'nutrition': {
      'Calories': '282 kcal',
      'Carbs': '50g',
      'Protein': '12g',
      'Fat': '14g',
    },
  },
  {
    'id': 'spice_5',
    'name': 'Garam Masala',
    'image': 'assets/garammasala.png',
    'rating': '⭐ 4.9 (520)',
    'price': 'Rs.200',
    'description':
        'A blend of organic spices for rich and bold Indian flavors.',
    'nutrition': {
      'Calories': '340 kcal',
      'Carbs': '45g',
      'Protein': '10g',
      'Fat': '20g',
    },
  },
  {
    'id': 'spice_6',
    'name': 'Black Pepper',
    'image': 'assets/blackpepper.png',
    'rating': '⭐ 4.8 (410)',
    'price': 'Rs.180',
    'description': 'Whole organic black peppercorns, packed with bold flavors.',
    'nutrition': {
      'Calories': '251 kcal',
      'Carbs': '64g',
      'Protein': '10g',
      'Fat': '3g',
    },
  },
  {
    'id': 'spice_7',
    'name': 'Cardamom',
    'image': 'assets/cardamom.png',
    'rating': '⭐ 4.9 (390)',
    'price': 'Rs.600',
    'description': 'Fragrant organic cardamom pods for a sweet-spicy aroma.',
    'nutrition': {
      'Calories': '311 kcal',
      'Carbs': '68g',
      'Protein': '11g',
      'Fat': '7g',
    },
  },
  {
    'id': 'spice_8',
    'name': 'Cloves',
    'image': 'assets/cloves.png',
    'rating': '⭐ 4.8 (360)',
    'price': 'Rs.350',
    'description': 'Strong and aromatic organic cloves for intense flavor.',
    'nutrition': {
      'Calories': '274 kcal',
      'Carbs': '66g',
      'Protein': '6g',
      'Fat': '13g',
    },
  },
  {
    'id': 'spice_9',
    'name': 'Cinnamon',
    'image': 'assets/cinnamon.png',
    'rating': '⭐ 4.7 (400)',
    'price': 'Rs.250',
    'description': 'Warm and sweet organic cinnamon sticks for rich aroma.',
    'nutrition': {
      'Calories': '247 kcal',
      'Carbs': '81g',
      'Protein': '4g',
      'Fat': '1g',
    },
  },
  {
    'id': 'spice_10',
    'name': 'Fenugreek Seeds',
    'image': 'assets/fenugreek.png',
    'rating': '⭐ 4.6 (300)',
    'price': 'Rs.130',
    'description':
        'Bitter yet flavorful organic fenugreek seeds for traditional dishes.',
    'nutrition': {
      'Calories': '323 kcal',
      'Carbs': '58g',
      'Protein': '23g',
      'Fat': '6g',
    },
  },
  {
    'id': 'spice_11',
    'name': 'Mustard Seeds',
    'image': 'assets/mustard.png',
    'rating': '⭐ 4.7 (320)',
    'price': 'Rs.110',
    'description':
        'Pungent organic mustard seeds, essential for Indian tempering.',
    'nutrition': {
      'Calories': '508 kcal',
      'Carbs': '28g',
      'Protein': '26g',
      'Fat': '36g',
    },
  },
  {
    'id': 'spice_12',
    'name': 'Bay Leaves',
    'image': 'assets/bayleaves.png',
    'rating': '⭐ 4.6 (290)',
    'price': 'Rs.100',
    'description': 'Fragrant organic bay leaves for rich, herbal notes.',
    'nutrition': {
      'Calories': '313 kcal',
      'Carbs': '75g',
      'Protein': '8g',
      'Fat': '8g',
    },
  },
];
